"""empty message

Revision ID: 6c61cb6db1c4
Revises: 
Create Date: 2020-12-11 22:03:53.253525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c61cb6db1c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='primary key'),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('movie_id', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('rate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('lastName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('userName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('userPass', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bio', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('isAdmin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('userName', 'user', ['userName'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.create_table('favorites',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='primary key'),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('movie_id', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate')
    op.drop_index('email', table_name='user')
    op.drop_index('userName', table_name='user')
    op.drop_table('user')
    op.drop_table('favorites')
    # ### end Alembic commands ###
